name: ci 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Libraries
        run: pip install mkdocs-material 
      - name: Deploy Page
        run: mkdocs gh-deploy --force
